### PR TITLE
Animation SplashScreen and Logo of the app has been added

### PR DESCRIPTION
**Pull request by Ayushh23**
#98 Animated SplashScreen
And i have also added logo for the application

## Checklist:
My code follows the style guidelines of this project
 I have performed a self-review of my code
 I have commented on my code, particularly in hard-to-understand areas
 My changes generate no new warnings

 In this contribution, I enhanced the user interface of the project by adding an engaging animated splash screen. The splash screen introduces users to the app with a smooth animation that features the application logo. Alongside the animation, a thoughtfully chosen quote is displayed in a unique font, giving the app a distinct personality and creating an inviting atmosphere right from the start.

Key contributions include:

**Animated Splash Screen: Implemented smooth and dynamic animations to enrich the user’s first interaction with the app.

Custom Font Quote: Added a quote in a unique font to complement the app's theme, enhancing its aesthetic appeal.

Logo Integration: Integrated the application’s logo into the splash screen, boosting brand visibility.**

Screenshot:
Screenshot 2024-10-15 200353

### CODE REVIEW

**Comment by Vishwajith-Shettigar** [comment]
@Ayushh23 thanks, here are few changes:
1. Remove app icon.
2. Remove sub heading on splash screen.

Rest are LGTM.

**Comment by Ayushh23** [comment]
I have done. Now please merge it

**Comment by Vishwajith-Shettigar** [comment]
Please update you screen recording or screenshots according to new changes.

**Comment by Vishwajith-Shettigar** [comment]
Resolve the conflicts.

**Comment by Ayushh23** [comment]
I have resolved all the conflicts
And also update the screenshot

**Comment by Vishwajith-Shettigar** [comment]
@Ayushh23 please include files or changes that are only necessary, rest should be removed.

**Comment by Ayushh23** [comment]
How will i do that?

**Comment by Vishwajith-Shettigar** [comment]
> How will i do that?


Delete unwanted files or undo changes and commit -> push.

**Comment by Ayushh23** [comment]
I have attached only 28 files which i have changed

**Pull request closed without merging**
