### PR TITLE
Change default marker to default image avatar

### PR DESCRIPTION
**Pull request by Gopal0Gupta**
## Description
#36 This modification ensures that when there is no image URL, the default avatar will be shown instead of the red marker.

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Vishwajith-Shettigar** [comment]
@Gopal0Gupta please fill all the necessary details in PR template. Don't modify PR template.

**Comment by Gopal0Gupta** [comment]
> @Gopal0Gupta please fill all the necessary details in PR template. Don't modify PR template.

actually i am facing some issues with my android studio due to which i am not able to run this app and can't upload screenshot.

**Comment by Gopal0Gupta** [comment]
should i leave the pr template incomplete?

**Comment by Vishwajith-Shettigar** [comment]
> > @Gopal0Gupta please fill all the necessary details in PR template. Don't modify PR template.
> 
> actually i am facing some issues with my android studio due to which i am not able to run this app and can't upload screenshot.

Please fix build issue and attach necessary details.

**Comment by Vishwajith-Shettigar** [comment]
> > @Gopal0Gupta please fill all the necessary details in PR template. Don't modify PR template.
> 
> actually i am facing some issues with my android studio due to which i am not able to run this app and can't upload screenshot.

Post your query in discussion with error log.

**Comment by Gopal0Gupta** [comment]
> > > @Gopal0Gupta please fill all the necessary details in PR template. Don't modify PR template.
> > 
> > 
> > actually i am facing some issues with my android studio due to which i am not able to run this app and can't upload screenshot.
> 
> Post your query in discussion with error log.

let me try to solve it last time

can you do one favor for me, can you run the app with changes that i made in your machine

**Comment by Vishwajith-Shettigar** [comment]
@Gopal0Gupta update your branch.

**Comment by Gopal0Gupta** [comment]
> @Gopal0Gupta update your branch.

Done

**Comment by Vishwajith-Shettigar** [comment]
@Gopal0Gupta it works. Thanks.

**Pull request merged**
