### PR TITLE
Introduce privacy policy page.

### LINKED ISSUE #45: [Enhancement] Change layout of Privacy Screen.
- Refactor the layouts of Privacy Screen to constraint layout.
- Why prefer Constraint layouts? [Article](https://android-developers.googleblog.com/2017/08/understanding-performance-benefits-of.html)

### LINKED ISSUE #83: [Feature] Introduce privacy policy page.
Introduce privacy policy page.

### PR DESCRIPTION
**Pull request by AdarshThakare**
## Description

Fixes #83
I have tried to successfully create the UI for privacy screen using frame-layout and constraint-layout in android studio. 

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas

 ## Screenshot 
Screenshot 2024-10-10 at 7 53 43 PM

## Screenshots / Screen Recordings
Screenshot 2024-10-10 at 8 00 19 PM

## Note: Only ask for review when you complete all above.
kindly review and convey the corrections needed for improvement.

### CODE REVIEW

**Comment by Vishwajith-Shettigar** [comment]
@AdarshThakare  the issue is about changing layout to constraint layout, but you seems like created privacy policy page.

**Comment by Vishwajith-Shettigar** [comment]
I will suggest you to create new privacy policy option in profile screen. And create new privacy policy screen for policy texts.

**Comment by Vishwajith-Shettigar** [comment]
Issue for this PR #83

**Comment by AdarshThakare** [comment]
> I will suggest you to create new privacy policy option in profile screen. And create new privacy policy screen for policy texts.

**Comment by AdarshThakare** [comment]
Got it. But i think it would be more appropriate to add the privacy policy screen as a item in privacy tab of profile screen.
Would that be ok?

**Comment by Vishwajith-Shettigar** [comment]
> Got it. But i think it would be more appropriate to add the privacy policy screen as a item in privacy tab of profile screen. Would that be ok?

Add an option "Privacy Policy" below "Account". We will refactor "Privacy" into "Settings" in future.
image

**Comment by AdarshThakare** [comment]
Ok on it

**Pull request closed without merging**
