### PR TITLE
Enhanced the Privacy Screen and its Dialogs

### PR DESCRIPTION
**Pull request by Darkeye14**
Issue number: #34 
This includes redesigning of the Privacy Screen and the UI of the dialogs.
Adhering to the stated requirements, 
* No extreme changes have been made to the color scheme
* Top app bar background color has been changed to match the screen background color.
* font size of the title has been increased and it has been positioned towards right and down.
* Dialog boxes have rounded corners with a border.
* Dialog buttons express dynamic coloring.
* Dialog title color has also been updated.

Screenshot 2024-10-25 013656
Screenshot 2024-10-25 013939
Screenshot 2024-10-25 014236

Self test has been made and no functionality has been tampered with.

Video Recording:
https://github.com/user-attachments/assets/0f0ff008-eb43-4672-ba1c-4969682d2222

I request you to kindly merge these changes!!
Thank You!

### CODE REVIEW

**Comment by Darkeye14** [comment]
Would you kindly add hactoberfest-accepted label on this? 
Thank You!!

**Comment by Vishwajith-Shettigar** [comment]
@Darkeye14 can you redesign save and cancel button also please?

**Comment by Darkeye14** [comment]
Sure sir, i'll do it within an hour!
Thank You!!

**Comment by Darkeye14** [comment]
should i create another pull request sir??

**Comment by Darkeye14** [comment]
Screenshot 2024-10-25 104725

The buttons have been updated.
Works well with both Dark and Light theme.
The same recording stands as no further changes have been made and hence the build is successful. 
Thank you for giving me an opportunity to contribute!!

**Review by Vishwajith-Shettigar — COMMENTED** [review]
Remove .idea folder.

**Comment by Darkeye14** [comment]
> Remove .idea folder.

I have removed the files that was generated in ./idea folder by me.
Thank You!!

**Comment by Vishwajith-Shettigar** [comment]
Thanks @Darkeye14 .

**Pull request merged**
